Features/sitemap (#12)
* --force symlfony.yml

* date fixture symlfony.yml

* migration fix  symlfony.yml

* datte->datetimeimmutable symlfony.yml

* doctrine.yaml config

* database-test

* test ci

* update view

* add sitemap.xml

diff --git a/.github/workflows/symfony.yml b/.github/workflows/symfony.yml
--- a/.github/workflows/symfony.yml
+++ b/.github/workflows/symfony.yml
@@ -9,8 +9,7 @@ jobs:
       mysql:
         image: mysql:latest
         env:
-          MYSQL_ALLOW_EMPTY_PASSWORD: false
-          MYSQL_ROOT_PASSWORD: password
+          MYSQL_ALLOW_EMPTY_PASSWORD: true
           MYSQL_DATABASE: main
         ports:
           - 3306/tcp
@@ -54,12 +53,11 @@ jobs:
       - name: Run Migration
         run: |
           composer require --dev symfony/orm-pack
-          php bin/console doctrine:database:drop --env=test
           php bin/console doctrine:database:create --env=test|| echo "No migrations found or schema update failed"
-          php bin/console doctrine:migrations:migrate || echo "No migrations found or migration failed"
-          php bin/console doctrine:fixtures:load --env=test
+          php bin/console doctrine:migrations:migrate --env=test 'DoctrineMigrations\Version20220324165140'|| echo "No migrations found or migration failed"
+          php bin/console doctrine:fixtures:load --env=test --append
         env:
-          DATABASE_URL: mysql://root:password@127.0.0.1:${{ job.services.mysql.ports['3306'] }}/main
+          DATABASE_URL: mysql://root:@127.0.0.1:${{ job.services.mysql.ports['3306'] }}/main
 
       - name: Install PHPUnit
         run: simple-phpunit install
