database modif

diff --git a/.github/workflows/symfony.yml b/.github/workflows/symfony.yml
--- a/.github/workflows/symfony.yml
+++ b/.github/workflows/symfony.yml
@@ -48,12 +48,14 @@ jobs:
           restore-keys: ${{ runner.os }}-composer-
 
       - name: Install Composer dependencies
-        run: composer install --no-progress --prefer-dist --optimize-autoloader --ignore-platform-reqs
+        run: composer install --no-progress --prefer-dist --optimize-autoloader
 
       - name: Run Migration
         run: |
+          php bin/console doctrine:database:create || echo "No migrations found or schema update failed"
           php bin/console doctrine:database:create --env=test|| echo "No migrations found or schema update failed"
-          php bin/console doctrine:migrations:migrate --env=test 'DoctrineMigrations\Version20220324165140'|| echo "No migrations found or migration failed"
+          php bin/console doctrine:migrations:migrate 'DoctrineMigrations\Version20220326185500'|| echo "No migrations found or migration failed"
+          php bin/console doctrine:migrations:migrate 'DoctrineMigrations\Version20220326185500' --env=test|| echo "No migrations found or migration failed"
           php bin/console doctrine:fixtures:load --env=test --append
         env:
           DATABASE_URL: mysql://u737804456_aadelbos:Flora1608@127.0.0.1:${{ job.services.mysql.ports['3306'] }}/u737804456_main
